name: Mike Leatres
favicon: null
layout_spectrum: 0.45540851214900613
typography_spectrum: 0.7316354403737932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.17305379593744874
  lightness: 0.3453141711652279
  saturation: 0.8320410582236946
  rhythmicContrast: 0.8033089530654252
purpose: []
